<?php

/**
 * Implements hook_preprocess_block().
 */
function multibanner_default_preprocess_block(&$variables) {
  if ($variables['elements']['#plugin_id'] === 'views_block:multibanner_default-block_default') {
    $variables['#attached']['library'][] = 'multibanner_default/multibanner_type_slider';
  }
  if ($variables['elements']['#plugin_id'] === 'views_block:multibanner_default-block_flex') {
    $variables['#attached']['library'][] = 'multibanner_default/multibanner_type_flex';
  }
}
